LABS = 4
BASE_RESEARCH_TARGET = 48 * LABS

# # Captain
# MAINTENANCE_DIFFICULTY_MULTIPLIER = 1
# FUEL_DIFFICULTY_MULTIPLIER = 1
# GOODS_DIFFICULTY_MULTIPLIER = 1
# FOOD_DIFFICULTY_MULTIPLIER = 1
# WEATHER = 'Dry' # ????
# RAINWATER_DIFFICULTY_MULTIPLIER = 1
# FARM_YIELD_DIFFICULTY_MULTIPLIER = 1
# TREE_GROWTH_DIFFICULTY_MULTIPLIER = 1
# UNITY_DIFFICULTY_MULTIPLIER = 1

# Admiral
MAINTENANCE_DIFFICULTY_MULTIPLIER = 1.25
FUEL_DIFFICULTY_MULTIPLIER = 1.15
GOODS_DIFFICULTY_MULTIPLIER = 1.20
FOOD_DIFFICULTY_MULTIPLIER = 1.20
WEATHER = 'Dry' # ????
RAINWATER_DIFFICULTY_MULTIPLIER = 0.8
FARM_YIELD_DIFFICULTY_MULTIPLIER = 0.75
TREE_GROWTH_DIFFICULTY_MULTIPLIER = 0.5
UNITY_DIFFICULTY_MULTIPLIER = 1.20